### ISSUE TITLE
Provider domain

### ISSUE THREAD

**Issue by indiketa** [zonaut/keycloak-extensions#7]
It's nearly impossible to use a new domain following this example. KC registers JPA... but it's unusable (no table created, no entity scanned). Tested with 11.0.3 (example version), 15.0.2 and 16.1.0

**Comment by zonaut** [comment]
As a test I've just cloned the repo, ran 'mvn clean install' and after that 'docker-compose up'.
I then checked the Postgres database and the table has been created.

Make sure the jar is picked up and deployed. You should see something like Starting deployment of "provider-domain-0.0.1-SNAPSHOT.jar" in the logs.

Let me know how it turns out and if it doesn't work attach your logs
